# Generated by Django 5.2.7 on 2025-12-01 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(choices=[('RX', 'Radiografía'), ('TAC', 'Tomografía (TAC)'), ('RMN', 'Resonancia Magnética'), ('ECO', 'Ecografía'), ('MAM', 'Mamografía'), ('OTHER', 'Otro')], default='OTHER', max_length=10, verbose_name='Tipo de Estudio')),
                ('study_date', models.DateField(verbose_name='Fecha del Estudio')),
                ('study_description', models.TextField(blank=True, null=True, verbose_name='Descripción del Estudio')),
                ('file_path', models.FileField(upload_to='medical_images/%Y/%m/%d/', verbose_name='Archivo')),
                ('file_hash', models.CharField(db_index=True, max_length=256, unique=True, verbose_name='Hash del Archivo')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='Tamaño del Archivo (bytes)')),
                ('modality', models.CharField(blank=True, choices=[('CR', 'Radiografía Digital (CR)'), ('DR', 'Radiografía Directa (DR)'), ('CT', 'Tomografía Computarizada (CT)'), ('MR', 'Resonancia Magnética (MR)'), ('US', 'Ultrasonido (US)'), ('XC', 'Radiografía Externa (XC)'), ('OTHER', 'Otra')], max_length=10, null=True, verbose_name='Modalidad')),
                ('institution', models.CharField(blank=True, max_length=255, null=True, verbose_name='Institución')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Carga')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_images', to='users.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imagen Médica',
                'verbose_name_plural': 'Imágenes Médicas',
                'ordering': ['-study_date'],
                'indexes': [models.Index(fields=['patient', '-study_date'], name='medical_ima_patient_8cb9e1_idx'), models.Index(fields=['study_type'], name='medical_ima_study_t_530f73_idx'), models.Index(fields=['uploaded_at'], name='medical_ima_uploade_c28a82_idx')],
            },
        ),
    ]
