# Generated by Django 5.2.7 on 2025-12-01 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Error'), ('VALIDATED', 'Validado'), ('DISCARDED', 'Descartado')], default='PENDING', max_length=20, verbose_name='Estado')),
                ('diagnosis_result', models.TextField(blank=True, null=True, verbose_name='Resultado del Diagnóstico')),
                ('confidence_level', models.FloatField(default=0.0, help_text='Porcentaje de confianza (0-100)', verbose_name='Nivel de Confianza (%)')),
                ('ai_observations', models.JSONField(blank=True, default=list, verbose_name='Observaciones de la IA')),
                ('heatmap_data', models.JSONField(blank=True, default=dict, verbose_name='Datos del Mapa de Calor')),
                ('model_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='Versión del Modelo')),
                ('processing_time', models.FloatField(blank=True, default=0.0, verbose_name='Tiempo de Procesamiento (s)')),
                ('doctor_comments', models.TextField(blank=True, null=True, verbose_name='Comentarios del Médico')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Validación')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensaje de Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completación')),
            ],
            options={
                'verbose_name': 'Diagnóstico IA',
                'verbose_name_plural': 'Diagnósticos IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosisLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Creado'), ('PROCESSING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Error'), ('VALIDATED', 'Validado'), ('DISCARDED', 'Descartado'), ('COMMENTED', 'Comentado'), ('UPDATED', 'Actualizado')], max_length=20, verbose_name='Acción')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Detalles')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Log de Diagnóstico',
                'verbose_name_plural': 'Logs de Diagnóstico',
                'ordering': ['-timestamp'],
            },
        ),
    ]
