# Generated by Django 5.2.7 on 2025-12-01 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnostico', '0001_initial'),
        ('medical_images', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aidiagnosis',
            name='images',
            field=models.ManyToManyField(related_name='diagnoses', to='medical_images.medicalimage'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='users.patient'),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aidiagnosis',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_diagnoses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='diagnosislog',
            name='diagnosis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='diagnostico.aidiagnosis'),
        ),
        migrations.AddField(
            model_name='diagnosislog',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aidiagnosis',
            index=models.Index(fields=['patient', '-created_at'], name='diagnostico_patient_35dab9_idx'),
        ),
        migrations.AddIndex(
            model_name='aidiagnosis',
            index=models.Index(fields=['status', '-created_at'], name='diagnostico_status_bfb689_idx'),
        ),
        migrations.AddIndex(
            model_name='aidiagnosis',
            index=models.Index(fields=['requested_by', '-created_at'], name='diagnostico_request_78c529_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosislog',
            index=models.Index(fields=['diagnosis', '-timestamp'], name='diagnostico_diagnos_c91a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosislog',
            index=models.Index(fields=['action', '-timestamp'], name='diagnostico_action_e8e16b_idx'),
        ),
    ]
